Repository Upjuyanolja/Upjuyanolja_BE, pull requests merged in 2023-12, with the labels that each got.

#4 feat: Entity 및 Repository 생성
  src/main/java/com/backoffice/upjuyanolja/UpjuyanoljaApplication.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Accommodation.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationImage.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationOption.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Address.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Category.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/Coupon.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponType.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/entity/Authority.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/entity/Member.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/repository/MemberRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/entity/PayMethod.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/entity/Reservation.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/entity/ReservationRoom.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/repository/ReservationRoomRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomImage.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomOption.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomPrice.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomRepository.java
  src/main/java/com/backoffice/upjuyanolja/global/common/BaseTime.java
  src/main/java/com/backoffice/upjuyanolja/global/config/JpaAuditConfiguration.java
  src/main/java/com/backoffice/upjuyanolja/global/config/JvmTimeZoneConfiguration.java
Labels: 🛠️feature, ⚙Setting

#8 feat: PR 빌드 및 테스트 자동화 CI 구현
  .github/workflows/gradle.yml
Labels: ⚙Setting

#16 feat: ErrorCode Enum 생성
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
Labels: 🛠️feature

#18 refactor: 객실 설명 필드 삭제
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
Labels: 🚧refactoring

#17 feat: API 공통 응답 Record 생성
  src/main/java/com/backoffice/upjuyanolja/global/common/ApiResponse.java
Labels: 🛠️feature

#20 feat: ApplicationException 생성
  src/main/java/com/backoffice/upjuyanolja/global/exception/ApplicationException.java
Labels: 🛠️feature

#21 feat: 오픈 API 데이터 수집 기능 구현
  build.gradle
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationImageRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/controller/OpenApiRestController.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/exception/InvalidDataException.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/exception/OpenApiException.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/service/OpenApiService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomImageRepository.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
Labels: 🛠️feature

#22 feat : 회원가입 기능 구현
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberController.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/request/SignUpRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/response/SignUpResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/entity/Member.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/exception/IncorrectPasswordException.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/exception/MemberEmailDuplicationException.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/repository/MemberRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberRegisterService.java
  src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationConfig.java
  src/main/java/com/backoffice/upjuyanolja/global/security/SecurityConfig.java
Labels: 🛠️feature

#25 refactor: 오픈 API 데이터 수집 예외 처리 수정
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/service/OpenApiService.java
Labels: 🚧refactoring

#29 feat: 글로벌 예외 처리 구현
  src/main/java/com/backoffice/upjuyanolja/global/common/ApiResponse.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/GlobalRestControllerAdvice.java
Labels: 🛠️feature

#30 feat: Spring REST Docs 설정
  .github/workflows/gradle.yml
  src/docs/asciidoc/index.adoc
  src/test/java/com/backoffice/upjuyanolja/global/config/RestDocsConfig.java
  src/test/java/com/backoffice/upjuyanolja/global/config/RestDocsSupport.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 📚document, ⚙Setting, ✅Test

#36 feat: 이메일 중복 검사 기능 구현
  src/docs/asciidoc/member/member-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberController.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/response/CheckEmailDuplicateResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/repository/MemberRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberRegisterService.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/docs/MemberControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/unit/controller/MemberControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/unit/repository/MemberRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/unit/service/MemberRegisterServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/global/util/RestDocsSupport.java
Labels: 📚document, 🛠️feature, 🚧refactoring, ✅Test

#35 #13 feat: 예약 관련 엔티티 수정
  src/main/java/com/backoffice/upjuyanolja/domain/payment/entity/PayMethod.java
  src/main/java/com/backoffice/upjuyanolja/domain/payment/entity/Payment.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/entity/Reservation.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/entity/ReservationRoom.java
Labels: 🛠️feature

#37 feat: 회원 정보 조회 기능 구현
  src/docs/asciidoc/member/member-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberController.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberGetService.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/docs/MemberControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/unit/controller/MemberControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/unit/service/MemberGetServiceTest.java
Labels: 📚document, 🛠️feature, ✅Test
