Repository Upjuyanolja/Upjuyanolja_BE, pull requests merged in 2024-01, with the labels that each got.

#44 feat: 쿠폰 Entity, Repository 우선 구현
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/Coupon.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponRoom.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponStatus.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponType.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/exception/WrongCouponInfoException.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRoomRepository.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
Labels: 🛠️feature, 🚧refactoring

#40 refactor: 객실 재고 및 상태 관리 기능 수정
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/service/OpenApiService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomStatus.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomStock.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomStockRepository.java
Labels: 🚧refactoring

#53 refactor: 카테고리 기획 변경을 반영한 수정
  .gitignore
  src/docs/asciidoc/index.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Accommodation.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationType.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Category.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/exception/WrongAccommodationTypeException.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/exception/WrongCategoryException.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/service/OpenApiService.java
  src/main/java/com/backoffice/upjuyanolja/global/common/ApiResponse.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/GlobalRestControllerAdvice.java
Labels: 🚧refactoring

#48 회원 도메인 Redis 도입
  build.gradle
  src/main/java/com/backoffice/upjuyanolja/domain/member/entity/RefreshToken.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/repository/RefreshTokenRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberAuthService.java
  src/main/java/com/backoffice/upjuyanolja/global/config/RedisConfiguration.java
  src/main/java/com/backoffice/upjuyanolja/global/redis/RedisService.java
  src/test/java/com/backoffice/upjuyanolja/global/security/jwt/redis/RedisServiceCrudTest.java
Labels: 🛠️feature

#61 refactor: 숙소 등록 API 문서 수정
  src/docs/asciidoc/index.adoc
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/docs/AccommodationControllerDocsTest.java
Labels: 📚document, 🧑🏻‍🔧fix, 🚧refactoring

#62 refactor: 회원 조회 기능 수정
  src/docs/asciidoc/member/member-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberAuthController.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/docs/MemberAuthControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/unit/controller/MemberAuthControllerTest.java
Labels: 📚document, 🚧refactoring, ✅Test

#65 업주 로그인 기능 구현
  .github/workflows/gradle.yml
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/OwnerAuthController.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/exception/InvalidRoleException.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/AuthServiceProvider.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberAuthService.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/OwnerAuthService.java
  src/main/java/com/backoffice/upjuyanolja/global/config/EmailConfiguration.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
Labels: 🛠️feature

#70 feat: Dockerfile 추가
  Dockerfile.txt
Labels: ⚙Setting

#71 feat: 보유 숙소 목록 조회 기능 구현
  src/docs/asciidoc/accommodation/accommodation-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/dto/response/AccommodationNameResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/dto/response/AccommodationOwnershipResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationOwnershipRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/usecase/AccommodationCommandUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/usecase/AccommodationQueryUseCase.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/docs/AccommodationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/controller/AccommodationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/repository/AccommodationOwnershipRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/service/AccommodationCommandServiceTest.java
Labels: 📚document, 🛠️feature, 🚧refactoring, ✅Test

#64 feat: 예약/예약 취소 내역 조회
  src/docs/asciidoc/reservation/reservation-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/controller/ReservationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/response/GetCanceledResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/response/GetReservedResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/entity/ReservationRoom.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/entity/ReservationStatus.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/exception/NoSuchReservationRoomException.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/repository/ReservationRoomRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/controller/ReservationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/repository/ReservationRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationServiceTest.java
Labels: 🛠️feature, 🤷🏻question, ✅Test

#72 fix: Dockerfile .txt 확장자 제거
  Dockerfile
Labels: 🐞bug, 🧑🏻‍🔧fix, ⚙Setting

#76 feat: Dockerfile 및 submodule copy 설정 추가
  Dockerfile
  build.gradle
Labels: ⚙Setting

#73 feat: 객실 추가 등록 기능 구현
  src/docs/asciidoc/room/room-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationOwnershipRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/usecase/AccommodationQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/service/OpenApiService.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/response/GetCanceledResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/response/GetReservedResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/controller/RoomController.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/request/RoomRegisterRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/response/RoomInfoResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/response/RoomResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/exception/InvalidTimeFormatException.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomCommandUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/NotOwnerException.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/repository/AccommodationOwnershipRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/service/AccommodationCommandServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/controller/ReservationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/repository/ReservationRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/docs/RoomControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/controller/RoomControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/repository/RoomRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomCommandServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomServiceTest.java
Labels: 📚document, 🛠️feature, 🚧refactoring, ✅Test

#77 feat&refactor: 포인트 연관 관계 수정 및 클래스 추가
  src/main/java/com/backoffice/upjuyanolja/domain/member/entity/Member.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/controller/PointController.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
Labels: 🚧refactoring

#81 feat: 객실 수정 기능 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/room/room-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/controller/RoomController.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/request/RoomImageAddRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/request/RoomImageDeleteRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/request/RoomOptionRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/request/RoomUpdateRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomOption.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomPrice.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/exception/InvalidRoomStatusException.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/exception/RoomImageNotFoundException.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomCommandUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
  src/main/java/com/backoffice/upjuyanolja/global/util/DateTimeParser.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/docs/RoomControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/controller/RoomControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomCommandServiceTest.java
Labels: 📚document, 🛠️feature, 🚧refactoring, ✅Test

#84 refactor: 숙소 데이터에 우편번호 추가
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/dto/request/AccommodationRegisterRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Address.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/service/OpenApiService.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/docs/AccommodationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/controller/AccommodationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/repository/AccommodationOwnershipRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/service/AccommodationCommandServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/controller/ReservationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/repository/ReservationRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/repository/RoomRepositoryTest.java
Labels: 🚧refactoring

#95 feat: 객실 목록 조회, 객실 상세 조회 기능 구현
  src/docs/asciidoc/room/room-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/room/controller/RoomController.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/request/RoomPageRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/response/RoomPageResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomCustomRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomCommandUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/global/util/QueryDslUtil.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/docs/RoomControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/controller/RoomControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/repository/RoomRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomCommandServiceTest.java
Labels: 📚document, 🛠️feature, 🚧refactoring, ✅Test

#96 #86 쿠폰 만들기(View Data) API 구현
  .gitignore
  src/docs/asciidoc/coupon/coupon-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/config/CouponProperties.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/CouponMakeRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/CouponRoomsRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/AccommodationResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponAccommodationResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponDetailResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponMakeViewResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponRoomsResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/Coupon.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponStatus.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponType.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountType.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/exception/InsufficientCouponStockException.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/exception/InvalidCouponInfoException.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/exception/InvalidRequestBodyException.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/exception/PointInsufficientException.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponBackofficePrincipalService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponBackofficeService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponValidationService.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/GlobalRestControllerAdvice.java
  src/main/java/com/backoffice/upjuyanolja/global/validator/IdValidator.java
  src/main/java/com/backoffice/upjuyanolja/global/validator/ValidId.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/docs/CouponBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountTypeTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/controller/CouponBackofficeControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/repository/CouponRepositoryTest.java
  src/test/resources/clear_table.sql
  src/test/resources/create_data.sql
Labels: 🛠️feature, 🚧refactoring

#97 feat: 객실 논리 삭제 기능 구현
  src/docs/asciidoc/room/room-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/room/controller/RoomController.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomCommandUseCase.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/docs/RoomControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/controller/RoomControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomCommandServiceTest.java
Labels: 📚document, 🛠️feature, 🚧refactoring, ✅Test

#98 feat: 숙소 상세 조회 기능
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponController.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponAccommodationResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponDetailResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponIssuanceResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponPageResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponRoomDetailResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponRoomResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponIssuance.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountType.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponIssuanceRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/entity/Member.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/response/RoomResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/exception/RoomStockNotFoundException.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomStockRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomCommandUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
Labels: 🛠️feature, 👁️‍🗨️revision

#101 refactor: 오픈 API로 가져온 숙소 소유권, 카테고리 설정 추가
  README.md
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/CategoryRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/request/SignUpRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/dto/AccommodationType.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/service/OpenApiService.java
Labels: 🚧refactoring

#99 feat: 예약 기능 구현
  build.gradle
  src/docs/asciidoc/reservation/reservation-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/payment/entity/PayMethod.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/controller/ReservationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/request/CreateReservationRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/exception/InvalidCouponException.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/exception/InvalidReservationInfoException.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/exception/PaymentFailureException.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationStockService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomStock.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomStockRepository.java
  src/main/java/com/backoffice/upjuyanolja/global/annotation/ConcurrencyControl.java
  src/main/java/com/backoffice/upjuyanolja/global/aspect/ConcurrencyAspect.java
  src/main/java/com/backoffice/upjuyanolja/global/config/RedisConfiguration.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/docs/AccommodationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/controller/AccommodationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/docs/CouponBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/controller/CouponBackofficeControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/docs/MemberAuthControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/unit/controller/MemberAuthControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/controller/ReservationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationStockServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/docs/RoomControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/controller/RoomControllerTest.java
Labels: 📚document, 🛠️feature, ✅Test

#103 hotfix : 현재 로그인한 사용자 조회 기능 오류 수정 및 입점DB 수정
  src/main/java/com/backoffice/upjuyanolja/domain/member/entity/Owner.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/OwnerAuthService.java
  src/main/java/com/backoffice/upjuyanolja/global/security/SecurityUtil.java
Labels: 🧑🏻‍🔧fix

#102 feat: 예약 취소 기능 구현
  src/docs/asciidoc/reservation/reservation-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRedeemRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/controller/ReservationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/entity/Reservation.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/exception/NoSuchReservationException.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationStockService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomStock.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/controller/ReservationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationServiceTest.java
Labels: 📚document, 🛠️feature, ✅Test

#113 fix: 바인드 익셉션 핸들링 수정
  src/main/java/com/backoffice/upjuyanolja/global/exception/GlobalRestControllerAdvice.java
Labels: 🧑🏻‍🔧fix

#125 fix: cors 에러 해결
  src/main/java/com/backoffice/upjuyanolja/global/config/CustomCorsConfiguration.java
  src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationConfig.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/docs/AccommodationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/docs/CouponBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/docs/RoomControllerDocsTest.java
Labels: 🧑🏻‍🔧fix, ⚙Setting

#126 fix: 숙소 전체 조회 전체 허용으로 수정
  src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationConfig.java
Labels: 🧑🏻‍🔧fix

#118 #94 쿠폰 만들기 API 구현
  src/docs/asciidoc/coupon/coupon-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/CouponMakeRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/CouponRoomsRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponMakeRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponRoomsRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/AccommodationResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponMakeViewResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponRoomsResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/Coupon.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponIssuance.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountType.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/exception/DatabaseException.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/exception/InsufficientPointsException.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponBackofficePrincipalService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponBackofficeService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponValidationService.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/Point.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/exception/PointInsufficientException.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/exception/PointNotFoundException.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointRepository.java
  src/main/java/com/backoffice/upjuyanolja/global/config/DummyDevInit.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/docs/CouponBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/controller/CouponBackofficeControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/repository/CouponRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/service/CouponBackofficeServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/service/DiscountTypeTest.java
  src/test/resources/clear_table.sql
  src/test/resources/create_data.sql
Labels: 🛠️feature

#127 fix: PR #124 머지 후 서버 에러 해결
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationStockService.java
  src/main/java/com/backoffice/upjuyanolja/global/concurrency/annotation/ConcurrencyControl.java
  src/main/java/com/backoffice/upjuyanolja/global/concurrency/aspect/ConcurrencyAspect.java
  src/main/java/com/backoffice/upjuyanolja/global/concurrency/aspect/TransactionAspect.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationStockServiceTest.java
Labels: 🐞bug, 🛠️feature, 🧑🏻‍🔧fix, 🚧refactoring

#130 perf: 미니프 숙소 조회 개선 및 오류 해결
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationCustomRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponController.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponAccommodationResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponIssuanceResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponShortResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/Coupon.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponIssuance.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountType.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponIssuanceRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponBackofficeService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/global/config/DummyDevInit.java
  src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationConfig.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/repository/CouponRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/service/DiscountTypeTest.java
Labels: 🧑🏻‍🔧fix, 🚧refactoring, 👁️‍🗨️revision

#132 Hotfix : 회원가입 관련 기능 수정
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberAuthController.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/OwnerAuthController.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/request/OwnerEmailRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/request/OwnerSignupRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/request/SignInRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/request/SignUpRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/response/OwnerSignupResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/exception/InvalidSignupProcessException.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberAuthService.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/OwnerAuthService.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
  src/main/java/com/backoffice/upjuyanolja/global/security/SecurityUtil.java
Labels: 🚧refactoring

#133 #109 feat: 쿠폰 관리 View API 구현 외 (rel. #119, #135)
  src/docs/asciidoc/coupon/coupon-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponAddInfos.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponAddRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponAddRooms.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponDeleteInfos.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponDeleteRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponDeleteRooms.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponModifyInfos.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponModifyRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponModifyRooms.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponRoomsRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponInfo.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponManageQueryDto.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponManageResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponManageRooms.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/Coupon.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountRestrictions.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountType.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponBackofficeService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
  src/main/java/com/backoffice/upjuyanolja/global/config/DummyDevInit.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/docs/CouponBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/controller/CouponBackofficeControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/repository/CouponRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/service/CouponBackofficeServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/service/DiscountTypeTest.java
Labels: 🛠️feature, 🚧refactoring

#137 feat: 미니프 카테고리, 쿠폰 수정
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationCustomRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/usecase/AccommodationCommandUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/CouponShortResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointChargesRepository.java
Labels: 🚧refactoring

#141 fix: b2b에서 admin으로 접속 가능하도록 수정
  src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationUserMappingService.java
Labels: 🧑🏻‍🔧fix

#142 fix: 객실 상태를 저장하지 않는 에러 해결
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
Labels: 🧑🏻‍🔧fix

#143 fix: 숙소 등록시 옵션, 객실, 이미지도 저장하도록 로직 추가
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationQueryService.java
Labels: 🧑🏻‍🔧fix

#140 refactor: 예약 목록 조회 원형에 필터 목적의 status 쿼리 파라미터 사용하도록 수정
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/controller/ReservationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/response/GetCanceledResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/response/GetReservationResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/response/GetReservedResponse.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/controller/ReservationControllerTest.java
Labels: 🚧refactoring

#147 Refactor: API Response Format 리팩토링
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponController.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberAuthController.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/OwnerAuthController.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/controller/OpenApiRestController.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/controller/PointController.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/controller/ReservationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/controller/RoomController.java
  src/main/java/com/backoffice/upjuyanolja/global/common/response/ApiResponse.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/docs/AccommodationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/controller/AccommodationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/docs/CouponBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/controller/CouponBackofficeControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/docs/MemberAuthControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/unit/controller/MemberAuthControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/controller/ReservationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/docs/RoomControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/controller/RoomControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/global/util/RestDocsSupport.java
Labels: 🚧refactoring

#149 refactor: 이메일 중복 검사 API를 POST 요청으로 수정
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberAuthController.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/request/EmailRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberAuthService.java
  src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationConfig.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/docs/MemberAuthControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/unit/controller/MemberAuthControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/member/unit/service/MemberAuthServiceTest.java
Labels: 🚧refactoring

#146 쿠폰 만들기 view api 버그 수정
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/config/CouponProperties.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponMakeRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountRestrictions.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountType.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponBackofficeService.java
  src/main/java/com/backoffice/upjuyanolja/global/security/SecurityConfig.java
  src/test/java/com/backoffice/upjuyanolja/httpTest/coupon/backoffice/coupon-getCreateCoupon.http
Labels: 🐞bug, 🧑🏻‍🔧fix

#151 Fix: roomStocks sort 전 가변 객체로 변환
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
Labels: 🐞bug, 🧑🏻‍🔧fix

#155 fix: 숙소 등록, 객실 등록 API 버그 수정
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomCustomRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomQueryUseCase.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/service/AccommodationCommandServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/repository/RoomRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomCommandServiceTest.java
Labels: 🧑🏻‍🔧fix

#157 Fix: 트랜젝션 롤백 에러
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
  src/main/java/com/backoffice/upjuyanolja/global/concurrency/aspect/TransactionAspect.java
Labels: 🐞bug, 🧑🏻‍🔧fix

#154 fix: onlyHasCoupon 동작 에러 해결
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
Labels: 🧑🏻‍🔧fix

#161 fix: 저장한 객실 이미지를 응답하기 위해 임시로 수정
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomCommandServiceTest.java
Labels: 🧑🏻‍🔧fix, 👁️‍🗨️revision

#162 feat: 로그아웃 기능 구현
  src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberAuthController.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberAuthService.java
  src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationConfig.java
Labels: 🛠️feature

#163 fix: 객실 목록 조회 시 쿠폰 데이터도 응답하도록 수정
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/response/RoomPageResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/response/RoomsInfoResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/docs/RoomControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/controller/RoomControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomCommandServiceTest.java
Labels: 🧑🏻‍🔧fix

#156 feat: 포인트 충전
  .github/workflows/gradle.yml
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/dto/response/OwnerInfoResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/member/repository/OwnerRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/controller/PointController.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/request/PointChargeRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointChargeResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/TossChargeResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/exception/PaymentAuthorizationFailedException.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/exception/TossApiErrorException.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointUsageCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
  src/main/java/com/backoffice/upjuyanolja/global/security/SecurityUtil.java
  src/test/java/com/backoffice/upjuyanolja/httpTest/member/insert/owner-signUp.http
  src/test/java/com/backoffice/upjuyanolja/httpTest/member/select/owner-signIn.http
  src/test/java/com/backoffice/upjuyanolja/httpTest/point/insert/point-charges.http
Labels: 🛠️feature

#165 refactor: 에러 코드 수정 및 RestDocs 업데이트
  src/docs/asciidoc/index.adoc
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
Labels: 📚document, 🚧refactoring

#169 #167 fix: 잘못된 토큰으로 ADMIN 권한이 필요한 요청시 9002 코드 응답하는 버그를 수정
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
  src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationConfig.java
Labels: 🐞bug, 🧑🏻‍🔧fix

#168 fix: 예약 시 쿠폰 적용 금액 계산 로직 수정
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
Labels: 🐞bug, 🧑🏻‍🔧fix

#170 feat: 포인트 환불
  src/main/java/com/backoffice/upjuyanolja/domain/point/controller/PointController.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/TossResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/Point.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointCharges.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/exception/WrongRefundInfoException.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
  src/test/java/com/backoffice/upjuyanolja/httpTest/point/delete/point-refunds.http
Labels: 🛠️feature, 👁️‍🗨️revision

#172 #171 fix: 비즈니스 요구 사항에 맞지 않는 에러 코드 응답 수정
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponAddRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/request/backoffice/CouponMakeRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponBackofficeService.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/docs/CouponBackofficeControllerDocsTest.java
Labels: 🐞bug, 🧑🏻‍🔧fix, 🚧refactoring

#175 feat: 예약 조회 시 최신순으로 정렬
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/controller/ReservationController.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/controller/ReservationControllerTest.java
Labels: 🛠️feature

#177 feat: 포인트 총액 조회 기능 개발
  src/main/java/com/backoffice/upjuyanolja/domain/point/controller/PointController.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointTotalBalanceResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointCharges.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
  src/test/java/com/backoffice/upjuyanolja/httpTest/point/select/point-getTotal.http
Labels: 🛠️feature

#178 feat: 객실 재고 생성 스케줄러 구현
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/global/scheduler/RoomStockScheduler.java
Labels: 🛠️feature, 🧑🏻‍🔧fix

#181 refactor: 포인트 충전 내역 조회 dto 변경
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointChargeDetailResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointUsageRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
Labels: 🚧refactoring

#180 refactor: 재고 조작을 가장 마지막에 하도록 리팩토링
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
  src/main/java/com/backoffice/upjuyanolja/global/concurrency/aspect/ConcurrencyAspect.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationServiceTest.java
Labels: 🐞bug, 🧑🏻‍🔧fix

#183 fix: 객실 수정 시 flush 하지 않아 수정되지 않는 점 수정
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
Labels: 🧑🏻‍🔧fix

#182 refactor: 락 점유시간, 대기시간 조정
  src/main/java/com/backoffice/upjuyanolja/global/concurrency/annotation/ConcurrencyControl.java
  src/main/java/com/backoffice/upjuyanolja/global/concurrency/aspect/TransactionAspect.java
Labels: 🐞bug, 🧑🏻‍🔧fix, 🚧refactoring

#185 refactor: 숙소, 객실 API URI 수정
  src/docs/asciidoc/accommodation/accommodation-api.adoc
  src/docs/asciidoc/image/image-api.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/controller/AccommodationBackofficeController.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/controller/ImageController.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/ImageService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/usecase/AccommodationCommandUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/controller/RoomController.java
  src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationConfig.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/docs/AccommodationBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/docs/ImageControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/controller/AccommodationBackofficeControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/controller/ImageControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/service/AccommodationCommandServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/service/ImageServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/docs/RoomControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/controller/RoomControllerTest.java
Labels: 🚧refactoring

#191 fix: 서버에서 이전에 발생하지 않았던 update timeout 발생으로 로직 순서 이전 버전으로 되돌림
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
Labels: 🐞bug, 🧑🏻‍🔧fix

#189 쿠폰 현황 통계 API 구현
  src/docs/asciidoc/coupon/coupon-api.adoc
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/dto/response/CouponStatisticsResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/CouponStatisticsDto.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/CouponStatisticsInterface.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponIssuance.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponStatistics.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponStatisticsRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponStatisticsService.java
  src/main/java/com/backoffice/upjuyanolja/global/scheduler/CouponStatisticsScheduler.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/docs/CouponBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/controller/CouponBackofficeControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/httpTest/coupon/backoffice/coupon-geCouponStatistics.http
Labels: 🛠️feature

#179 feat: 포인트 사용한 쿠폰 결제 기능 개발
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/usecase/AccommodationQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/CouponIssuance.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponBackofficeService.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/controller/PointController.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/Point.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointCharges.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointRefunds.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointStatus.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointUsage.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointChargesCustomRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointChargesCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointChargesRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
Labels: 🛠️feature, 🚧refactoring, 👁️‍🗨️revision

#193 hotfix: 재고 조작 순서 변경
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
Labels: 🐞bug, 🧑🏻‍🔧fix

#194 fix: 상위 카테고리도 검색하는 오류 해결
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationQueryService.java
Labels: 🧑🏻‍🔧fix

#195 feat: 모든 포인트 내역 조회
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponIssuanceRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponIssuanceGetService.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/controller/PointController.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointTotalDetailResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointTotalPageResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointUsageCouponReceiptResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointUsageDetailReceiptResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointUsageDetailResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointUsagePageResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointUsageReceiptResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointUsageRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
  src/test/java/com/backoffice/upjuyanolja/httpTest/point/select/point-getTotalBalance.http
  src/test/java/com/backoffice/upjuyanolja/httpTest/point/select/point-getTotalPoint.http
  src/test/java/com/backoffice/upjuyanolja/httpTest/point/select/point-getUsagePoint.http
Labels: 🛠️feature, 🚧refactoring, 👁️‍🗨️revision

#196 fix: 포인트 총액 조회 url 수정
  src/main/java/com/backoffice/upjuyanolja/domain/point/controller/PointController.java
Labels: 🧑🏻‍🔧fix

#197 fix: 포인트 내역 조회에서 날짜를 String 형식으로 통일해서 다룸
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointChargeResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointTotalDetailResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
  src/test/java/com/backoffice/upjuyanolja/httpTest/point/select/point-getTotalBalance.http
Labels: 🧑🏻‍🔧fix

#198 fix: 쿠폰 사용 내역 조회 영수증 수정
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
Labels: 🧑🏻‍🔧fix

#203 fix: 쿠폰 통계 쿼리에 대문자를 소문자로 수정
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponStatisticsRepository.java
Labels: 🧑🏻‍🔧fix

#204 fix: 오타 수정
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponStatisticsRepository.java
Labels: 🧑🏻‍🔧fix

#200 fix: 포인트 전체 내역 조회 페이징 수정
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointUsageRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
Labels: 🧑🏻‍🔧fix

#205 fix: 남은 대문자도 모두 소문자로 수정
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/RevenueStatisticsRepository.java
Labels: 🧑🏻‍🔧fix

#201 fix: enable 쿠폰만 조회 가능 하도록 수정
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
Labels: 🧑🏻‍🔧fix

#202 fix: 숙소 검색 결과가 없을 경우 빈 리스트 반환
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
Labels: 🧑🏻‍🔧fix

#206 feat: 토스 응답 필드 추가
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointChargeReceiptResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/TossResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointCharges.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
Labels: 🛠️feature

#207 fix: 숙소 관련된 쿠폰들은 모두 상태로 걸러지도록 수정
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
Labels: 🧑🏻‍🔧fix

#208 fix: 잘못 설정 해 놓은 url 고침
  src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationConfig.java
Labels: 🧑🏻‍🔧fix

#210 fix: totalBalance 구하는 방식 변경
  src/main/java/com/backoffice/upjuyanolja/domain/point/exception/PointTradeFailedException.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
Labels: 🧑🏻‍🔧fix

#212 refactor: 마지막 객실 삭제 시 에러 처리 추가
  src/main/java/com/backoffice/upjuyanolja/domain/room/exception/CanNotDeleteLastRoomException.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
Labels: 🚧refactoring

#213 docs: 리드미 수정
  README.md
  src/main/resources/images/architecture.png
  src/main/resources/images/cicd.jpg
  src/main/resources/images/cicd.png
  src/main/resources/images/erd.png
  src/main/resources/images/main.jpg
Labels: 📚document

#214 docs: 리드미 역할 수정
  README.md
Labels: 📚document

#215 docs: FE 배포 서버 URL 추가
  README.md
Labels: 📚document

#216 fix: 포인트 도메인 주요 문제 모두 해결
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointChargeDetailResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointUsageReceiptResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointCategory.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointStatus.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointType.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointUsage.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointChargesCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
Labels: 🧑🏻‍🔧fix, 🚧refactoring

#219 fix: 포인트 환불 및 사용 에러 해결
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
Labels: 🧑🏻‍🔧fix

#220 refactor: 포인트 내역 조회 dto 수정
  src/main/java/com/backoffice/upjuyanolja/domain/point/dto/response/PointTotalDetailResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
Labels: 🚧refactoring

#221 fix: 쿠폰 만들기 포인트 결제 수정
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
Labels: 🧑🏻‍🔧fix

#218 #217 fix: 통계 쿼리 호환성 버그 수정
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/config/MockStatisticsInit.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponStatisticsRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/RevenueStatisticsRepository.java
Labels: 🐞bug, 🧑🏻‍🔧fix

#223 refactor: 페이지 정렬과 포인트 상태 설명 변경
  src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointStatus.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointChargesRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/repository/PointUsageRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
Labels: 🚧refactoring

#222 refactor: CQRS 수정
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/controller/AccommodationBackofficeController.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/usecase/AccommodationCommandUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/usecase/AccommodationQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponBackofficeService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/controller/RoomController.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomCommandUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomQueryUseCase.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/docs/AccommodationBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/controller/AccommodationBackofficeControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/service/AccommodationCommandServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/service/AccommodationQueryServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/docs/RoomControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/controller/RoomControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomCommandServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomQueryServiceTest.java
Labels: 🚧refactoring

#224 refactor: reservation-payment 관계 수정 및 재고 차감 예외처리 추가
  src/main/java/com/backoffice/upjuyanolja/domain/payment/entity/Payment.java
  src/main/java/com/backoffice/upjuyanolja/domain/payment/repository/PaymentRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/response/GetCanceledResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/response/GetReservationResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/dto/response/GetReservedResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/entity/Reservation.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/controller/ReservationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/repository/ReservationRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationServiceTest.java
Labels: 🚧refactoring
