Repository Upjuyanolja/Upjuyanolja_BE, pull requests merged in 2024-02, with the labels that each got.

#225 refactor: 포인트와 숙소 가독성 개선
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
  src/main/java/com/backoffice/upjuyanolja/domain/point/service/PointService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomQueryService.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomQueryServiceTest.java
Labels: 🚧refactoring, 👁️‍🗨️revision

#226 fix: 쿠폰 재고 감소 시 누락된 숙소 재고 보상 트랜젝션 추가
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
Labels: 🧑🏻‍🔧fix

#227 refactor: erd 변경과 코드 수정
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/dto/request/AccommodationOptionRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/dto/request/AccommodationRegisterRequest.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/dto/response/AccommodationDetailResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/dto/response/AccommodationInfoResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/dto/response/AccommodationSummaryResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Accommodation.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationOption.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Address.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/exception/AccommodationOptionNotFoundException.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationImageRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/repository/AccommodationOptionRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/usecase/AccommodationQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/coupon/service/CouponService.java
  src/main/java/com/backoffice/upjuyanolja/domain/openapi/service/OpenApiService.java
  src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/response/RoomInfoResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/response/RoomResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/dto/response/RoomsInfoResponse.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomOption.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomPrice.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/exception/RoomOptionNotFoundException.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/exception/RoomPriceNotFoundException.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomCustomRepositoryImpl.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomImageRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomOptionRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomPriceRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/repository/RoomRepository.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomCommandService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/RoomQueryService.java
  src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomQueryUseCase.java
  src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/docs/AccommodationBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/repository/AccommodationOwnershipRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/service/AccommodationCommandServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/accommodation/unit/service/AccommodationQueryServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/docs/CouponBackofficeControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/controller/CouponBackofficeControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/repository/CouponRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/coupon/unit/service/CouponBackofficeServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/controller/ReservationControllerTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/repository/ReservationRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/reservation/unit/service/ReservationStockServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/repository/RoomRepositoryTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomCommandServiceTest.java
  src/test/java/com/backoffice/upjuyanolja/domain/room/unit/service/RoomQueryServiceTest.java
Labels: 🚧refactoring
